# Generated by Django 3.1 on 2020-10-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url3',
        ),
    ]
